[package]
name = "day-7"
version = "0.1.0"
authors = ["Nathaniel J Cochran <nathanjcochran@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
